### ISSUE TITLE
App keeps reloading

### ISSUE THREAD

**Issue by viditmaniyar** [GetStream/stream-react-example#10]
I tried tutorial 1 a few weeks ago and at the end of it - It was working just fine. Then after a break I resumed and I re-ran it after Tutorial 6 and it'd do nothing but it kept reloading. I see the `Loading...` on the browser and nothing else. I thought I misconfigured it so I did a new clone and retried tutorial 1 but it still the same.

Any pointers?

**Comment by astrotars** [comment]
Hey @iamrudra, I apologize for the delay... Have you tried swapping out the Facebook App ID in the index.ejs file in /app? That should fix the reload issue, assuming that you don't have any other errors popping up in your console. On that note, what browser/OS are you running?

**Comment by viditmaniyar** [comment]
@nparsons08 - No worries man! I used OSX + Chrome. And just recalled that I was facing some error indeed. I had not put the MapBox credentials and that was throwing an error but I don't that that was causing the reload.
Here's **why** - 

I started afresh on my Ubuntu 16.04 machine (+Chrome) yesterday again from the scratch and this time I could see the landing page without issues.

**Comment by astrotars** [comment]
Perfect. So you're up and running now? :) 👍

**Comment by viditmaniyar** [comment]
@nparsons08 - Technically not yet on the machine that I faced problems in the first place but you can keep this closed. I will try and reproduce and let you know.

**Comment by astrotars** [comment]
Sounds good. Happy to help.
