### ISSUE TITLE
API and the UX shows error but the image is uploaded to S3

### ISSUE THREAD

**Issue by viditmaniyar** [GetStream/stream-react-example#11]
After the part in the series where I configured IMGX, Algolia and Keen, I tried uploading an image out of curiosity. But saw an error message on the upload button as well as the API since I had not put the MapBox credentials. 

Even then, the images got uploaded to the S3 bucket. Ideally this should have _not_ been uploaded since it's an error on API and UX.

OS: Ubuntu 16.04; Browser: Chrome

**Comment by nparsons08** [comment]
Dupe

**Comment by viditmaniyar** [comment]
@nparsons08 - Sorry I didn't get that. If you meant duplicate, then nope. This is an entirely separate issue. 

#10 was about app breaking and keeps refreshing and does not show anything except `Loading...` and this is about unintentional uploads and inconsistency in frontend and backend

**Comment by iamrudra** [comment]
#10 was about app breaking and keeps refreshing and does not show anything except `Loading...` and this is about unintentional uploads and inconsistency in frontend and backend

**Comment by astrotars** [comment]
I see. What is the error message that you're seeing? @iamrudra

**Comment by astrotars** [comment]
@iamrudra feel free to email me directly at nick@getstream.io to continue the conversation there.

**Comment by viditmaniyar** [comment]
@nparsons08 - Sorry for the delay didnt get a chance to send you the screenshots yesterday. Will do it today evening PST.

**Comment by viditmaniyar** [comment]
@nparsons08  - 

### To reproduce:
1. Remove your `mapbox_access_token` from the `env.sh` file. 
2. Go to the `localhost:3000/upload`, select an image and click the upload button.
3. The api console will show error that mapbox credentials needs to be added - 
   ![api_error](https://cloud.githubusercontent.com/assets/12117759/17465674/54559ec4-5cb3-11e6-8435-ac5ac7a351cb.png)
   The UI in the browser also shows internal error and the error message - 
   ![ux_error](https://cloud.githubusercontent.com/assets/12117759/17465701/1455008e-5cb4-11e6-84b5-d7d6286a0e09.png)
4. **Problem** -> Irrespective of these `correct` error messages on the client side, the image gets uploaded to the `S3 bucket` on `AWS`
   ![s3_bucket](https://cloud.githubusercontent.com/assets/12117759/17465675/54566ab6-5cb3-11e6-90f0-1cccd164a8a7.png)

**Comment by astrotars** [comment]
What version of node are you running @iamrudra?

**Comment by viditmaniyar** [comment]
@nparsons08

```
node - 4.2.8
npm - 3.5.2
OS - Ubuntu 16.04
Browser - Google Chrome
```

**Comment by astrotars** [comment]
Can you first try upgrading to a 5.x branch of node? @iamrudra
