### ISSUE TITLE
Connection Timeout @ http://cabin.getstream.io:3000/

### ISSUE THREAD

**Issue by MarkMurphy** [GetStream/stream-react-example#12]
I'm not sure if you've noticed but the live demo at http://cabin.getstream.io/demo seems to be broken. 

The web console shows the following error:

```
http://cabin.getstream.io:3000/ Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
```

**Comment by MarkMurphy** [comment]
@nparsons08 ?

**Comment by astrotars** [comment]
@MarkMurphy We've confirmed it's working on our end (http://cabin.getstream.io:3000/). Do you see any errors in your console that you can share? Also, what OS and browser / version are you using? Thanks!

**Comment by MarkMurphy** [comment]
Still not working for me:

Chrome 52.0.2743.116 (64-bit) on Mac OS X El Capitan 10.11.5

![screenshot 2016-08-22 15 37 00](https://cloud.githubusercontent.com/assets/873474/17866808/5d316e3e-687e-11e6-8f0e-d77d3d0ff942.png)
![screenshot 2016-08-22 15 38 28](https://cloud.githubusercontent.com/assets/873474/17866856/83f166fa-687e-11e6-98ce-58920174b43b.png)

**Comment by astrotars** [comment]
Thank you for sharing. That's very odd behavior. Are you able to load the site up on a cell phone to see if it loads there? Perhaps a plugin of sorts is blocking (wild guess)?

**Comment by MarkMurphy** [comment]
Yeah super weird. Seems like it works on my iphone except that it's choking on my last name apparently being null. 

Just out of curiosity, I tried it on Safari on my Mac and had the same issue. I'm beginning to suspect that it might just be the network configuration of the office building I'm in. There's a high probability they're blocking that port. I'll try it again at home tonight and see what happens.

**Comment by MarkMurphy** [comment]
Actually, just confirmed it. That port is blocked on our office network. Don't know why I didn't think of that sooner, first time it's become an issue I guess.
