### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by giladaya** [GetStream/stream-react-example#15]
Was getting an error after each upload and traced it back to this line: 
https://github.com/GetStream/stream-react-example/blob/de0c1e890c741c19efc25b0a2040349e142200ac/app/modules/actions/Stream.js#L19

I believe it should be `data.new.map` instead of `data.news.map`

Thanks

**Comment by astrotars** [comment]
@giladaya Thanks for the heads up! Would you mind submitting a PR?

**Comment by giladaya** [comment]
Ok, might take me some time though...
