### ISSUE TITLE
Upload not working 😞

### ISSUE THREAD

**Issue by ArchieHicklin** [GetStream/stream-react-example#19]
Everytime an upload request is made, it returns:

`POST http://localhost:8000/uploads 500 (Internal Server Error)`

No error in the terminal, just this error in the console.

**Comment by dwightgunning** [comment]
Hi Archie,

This may be related to the various integrations that are triggered when uploading (Imgix, Mapbox, Keen). The application isn't fully functional when you first clone the repo as there is some extra setup required.

Check your env.sh and if you've not got all the keys/secrets setup then that's likely to be the cause of the problem.

When we created the guide we intended/expected people would step through the tutorial without skipping ahead too much. I'm planning to look into ways to make the  error messages simpler to understand (in the context of the tutorials).

**Comment by ArchieHicklin** [comment]
@dwightgunning Thanks for the reply,

Still get the same error persisting even after the recent pushes 😭

Navigating to `http://localhost:8000/uploads`

returns the message

`{"code":"InvalidCredentials","message":"No authorization token was found"}`

Went slowly through the entire tutorial and env.sh is completely filled out with the various api keys.

Would it be possible to send you or someone else my env.sh to have a look? I'm only testing the various integrations on this build so key exposure isn't a worry. 👏

**Comment by dwightgunning** [comment]
Sorry for the slow response. Feel free to send it to dwight@getstream.io
