### ISSUE TITLE
Demo & "Run Webpack & Check Out Your App"  not working with Facebook Logged In

### ISSUE THREAD

**Issue by toyeebgodo** [GetStream/stream-react-example#28]
Hi guys, thanks for the wonderful work that went into putting together this great tutorial. Before proceeding with the tutorial, I attempted to give the demo a go by logging in through Facebook. It didn't log me in and it kept displaying "loading" continuously.  I ignored everything and proceeded to build the app by following the tutorial directives.

After running "npm start" and opening http://localhost:3000 at the "Run Webpack & Check Out Your App" section of the tutorial, instead of getting the landing page, I got the  continuous message, "loading." 

Immediately I logged out of my Facebook in the browser, however, the landing page showed. I am guessing there is a problem with my Facebook . I have gone to check my Facebook settings to make sure that I have given the proper permissions. Again, I can't take the demo app for a spin through Facebook logging in and my app's landing page won't run while Facebook is logged in. The problem is the same in my Google Chrome, internet explorer, and Firefox. I am also using a Windows 7 PC, by the way. Gracias for your help.

**Comment by dwightgunning** [comment]
Thanks for the report!

Unfortunately this isn't the first time I've noticed the issue, but I had thought it was only effecting my personal Facebook account. I will try to replicate it again and take a closer look at the issue.

Stay tuned.

**Comment by astrotars** [comment]
Hey @toyeebgodo, we're working on improvements to the application now. Generally, your issue can arise due to one of two problems. 1) you did now allow for us to collect your email during the authentication step, or 2) the API was malfunctioning and there was a connection issue. Both can happen locally as well. Closing this for now; however, please reopen or ping me directly if you are having issues. Thanks!

**Comment by toyeebgodo** [comment]
Thank you so much for your kind attention to this, @dwightgunning and @nparsons08. Facebook login is now working, maybe it was an API malfunction.  I am deeply grateful to you guys for the wonderful work of putting together such an extremely detailed and complex app. I am a huge fan. Thanks a billion for the recommendation of Tyler McGinnis' React tutorial.

**Comment by vincentroman** [comment]
@toyeebgodo please how did you get facebook login to work for you cus am hhaving issue with the api not allowing GET
