### ISSUE TITLE
Demo wont load

### ISSUE THREAD

**Issue by JeffreyCheng92** [GetStream/stream-react-example#3]
After connecting to the demo with OAuth (I didnt provide my email address in the provided information), an infinite cycle of post/exceptions occur. The iframe is just forever `loading..`

`external "react":1POST http://cabin.getstream.io:8000/users 500 (Internal Server Error)`

`external "react":1Uncaught (in promise) TypeError: Cannot read property 'notification' of undefined(…)`

**Comment by astrotars** [comment]
@JeffreyCheng92 I'm assuming that you connected with Facebook, right? In that case, did you allow all permissions? Our application requires that you provide an email address. If you'd like to load the demo, please uninstall the application by visiting your [application settings](https://www.facebook.com/settings?tab=applications). Sorry for the trouble!

**Comment by wsdt** [comment]
After removing it from the Facebook applications, the issue is still there by logging in with Facebook again (all permissions granted).
