### ISSUE TITLE
Demo still not working

### ISSUE THREAD

**Issue by vladfulgeanu** [GetStream/stream-react-example#4]
When I try to connect with Facebook, although I enable the email scope 

![selection_026_censored](https://cloud.githubusercontent.com/assets/1254006/16519477/eff7d192-3f91-11e6-9e66-87cc84deec80.jpg)

I get these errors in the API several times:
- "The following feeds are not configured: 'timeline_flat'"
- "The following feeds are not configured: 'notification'"
- "The following feeds are not configured: 'timeline_aggregated'"

**Comment by tschellenbach** [comment]
It sounds as though your Stream account isn't correctly configured. See step 4: http://cabin.getstream.io/

**Comment by vladfulgeanu** [comment]
I don't know if that's the case. The Stream's dashboard confirms there were 34 API calls.

**Comment by tschellenbach** [comment]
http://blog.getstream.io/cabin-react-redux-example-app-stream/

Search for: Setting Up Stream

Specifically this part:

"Next, create a new application in the dashboard with the following feed groups and types:

user_posts (flat)
user (flat)
timeline_flat (flat)
timeline_aggregrated (aggregated)
notification (notification)"

**Comment by tschellenbach** [comment]
Maybe you've created 2 applications. Setup the feed groups for 1 of the applications, but are using the API keys of the other one?

**Comment by vladfulgeanu** [comment]
![selection_027](https://cloud.githubusercontent.com/assets/1254006/16523218/ddeb5e10-3faa-11e6-86dc-f74bedede905.png)

**Comment by tschellenbach** [comment]
Which API key are you using? Is that the same one as this app?

**Comment by vladfulgeanu** [comment]
yes, it's the same as the one on this app

**Comment by tschellenbach** [comment]
Might be an issue with your environment variable changes not being picked up. Try rerunning these 3 steps:
- Run webpack to pickup on changes in /app by running source ../env.sh; webpack --watch --progress
- In a terminal window, cd into the directory for /app then source ../env.sh; npm start
- In a terminal window, cd into the directory for /api then source ../env.sh; nodemon

**Comment by vladfulgeanu** [comment]
Still no luck. I've tried running all three (webpack, api, app) with the environment in env.sh after deleting the Facebook app, although in [here](http://blog.getstream.io/cabin-react-redux-example-app-introduction#todo-20) it doesn't specify to run the app with the environment.

**Comment by tschellenbach** [comment]
I'm out of ideas. Somehow the API isn't querying the right app. @nparsons08 any thoughts?

**Comment by astrotars** [comment]
@fullvlad Sorry for the delay. Are you able to jump on a quick video chat? I'm happy to help debug there. Let me know and we can set something up on http://appear.in/

**Comment by vladfulgeanu** [comment]
hey, @nparsons08, yes, how should I enter?

**Comment by astrotars** [comment]
@fullvlad I'll wait for you in https://appear.in/stream. See you soon! :)

**Comment by vladfulgeanu** [comment]
@nparsons08 wow, I've just found right now what was the culprit. As you can see in my stream.io Feeds Groups screenshot, I entered "timeline_aggregrated" with a typo because I copied it from @tschellenbach's comment. I edited it now, and it works :D

**Comment by tschellenbach** [comment]
Which I copied from the blogpost, brilliant :)
http://blog.getstream.io/cabin-react-redux-example-app-stream/

**Comment by vladfulgeanu** [comment]
lol ... at least we've found this typo.
thanks a lot for your help and close inputs!

**Comment by astrotars** [comment]
@fullvlad Nice find! Let us know if there's anything else you need help with.
