### ISSUE TITLE
App won't load

### ISSUE THREAD

**Issue by EliSadaka** [GetStream/stream-react-example#42]
I'm trying to run the app by following the instructions here: [https://getstream.io/blog/cabin-react-redux-introduction/](https://getstream.io/blog/cabin-react-redux-introduction/)

I followed all the steps but when I go to http://localhost:3000 I get a blank page and my console reads like this:
![error](https://user-images.githubusercontent.com/35779188/35352274-6fd1fab8-0111-11e8-867d-b70e675e114e.PNG)

What's causing this error?

**Comment by gmorneault** [comment]
Getting the same error.

**Comment by EliSadaka** [comment]
I fixed my issue by downgrading react and react-dom to 15.6.2 and react-router to 3.2.0.

**Comment by daletom** [comment]
Hey EliSadaka, how would I go about downgrading react and react-dom to 15.6.2 and react-router to 3.2.0.

**Comment by EliSadaka** [comment]
In the /app folder:

`npm install react@15.6.2 react-dom@15.6.2 react-router@3.2.0`

**Comment by ericsolberg** [comment]
I was sure hoping to be able to use this tutorial, but have now spent an entire weekend on step 1. There are very specific dependencies for everything, but these aren't mentioned (I ended up figuring it out based on the publish date of the tutorial- guessing at the versions based on what was out at that time). 

I worked through one roadblock at a time. Initially I found myself removing and re-installing different modules with brew on my mac, and I started suspecting that things were just too "unclean" to get the right versions of things working together. So I started creating a docker container, building it up a bit at a time based on what I found to work and not work.

I ended up with: Ubuntu 16.0.4, Python 2.7, Node 9.2.1, Webpack 2.6.1, and MySQL 5.6 (5.7 seems to work but getting it to install with apt-get in a Dockerfile was problematic). 

With this configuration, the "npm install" steps completed, webpack completed, and the api and app startups were all error-free. But then I got the blank app page as others have noted in this issue. I followed the advice to "npm install react@15.6.2 react-dom@15.6.2 react-router@3.2.0" in the app directory. Now I at least have an image background  in the browser and "Continue with Facebook" in the bottom (which doesn't work). But clearly I still don't have the whole app running.

I was really hoping to work through this tutorial to help me get up and running with React and Getstream. But it looks like this is hopelessly out of date and I'm just going to keep encountering road blocks, and the lost time is accumulating. 

Perhaps I've just gone down the wrong path, making things harder for myself? If anyone is able to make this work in an up-to-date late 2018 stack (Mac or Docker), please let me know the versions/steps. Thanks!

**Comment by ericsolberg** [comment]
I created a Github project of the Docker file I used to work through all the dependencies and make this tutorial work. If anyone finds it useful:
https://github.com/ericsolberg/cabin

**Comment by vincentroman** [comment]
@ericsolberg please did you get the app to work after clicking the continue with facebook if yes please share your code with me i also have been working on getting it pass the facebook login
