### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by anthonybrown** [GetStream/stream-react-example#44]
Seems like the demo is not working?
All I see is a blank page.

Opening the console, I see that `Keen` is not defined?

**Comment by KarlsDad** [comment]
also here, whats wrong?
only the "Loading..." Message can be seen

**Comment by dwightgunning** [comment]
This demo app runs on quite a small server, occasionally it needs a nudge. Issue should be resolved now and the demo app up and running again.

**Comment by jigyasam** [comment]
@dwightgunning Its down again. Culprit seems to be this `POST` call `http://cabin.getstream.io:8000/users`.

**Comment by vincentroman** [comment]
please  can this app be developed loacally on windows or ubuntu latest versions ?

**Comment by dwightgunning** [comment]
@vincentroman - Yes it should be fairly straight forward to run this web application on Windows or Ubuntu.
