### ISSUE TITLE
Live demo not working

### ISSUE THREAD

**Issue by manjulrajeevpathak** [GetStream/stream-react-example#48]
The live demo at "https://getstream.io/cabin/demo" doesn't load at all. 
It gets stuck on "Loading..." screen
 
There is one console log --

Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.

**Comment by dwightgunning** [comment]
Thanks for the report. We've made a fix and the demo is up again.
