### ISSUE TITLE
App is not working 

### ISSUE THREAD

**Issue by rahuldwivedi** [GetStream/stream-react-example#49]
Hello there I have go through with tha app setup steps but when I am hitting on http://localhost:3000

I am having error message on chrome console attaching screenshot please have a look
![screenshot from 2018-05-31 12-38-46](https://user-images.githubusercontent.com/14931585/40767380-fda0bd94-64cf-11e8-983d-ec7bf0e2aeaf.png)

**Comment by dwightgunning** [comment]
That looks like a syntax error in the `app.js` file. Have you taken a closer look at this file to ensure it's built correctly?

**Comment by vincentroman** [comment]
can  you please help me with your own app.js code
