### ISSUE TITLE
UNMET PEER DEPENDENCY react@15.1.0

### ISSUE THREAD

**Issue by niccolox** [GetStream/stream-react-example#5]
hi

on Ubuntu Xenial host

working through the tutorials and getting this error

http://blog.getstream.io/cabin-react-redux-example-app-stream/

```
npm install getstream --save
app@1.0.0 /home/devekko/Projects/cabon-app/stream-react-example/app
├── getstream@3.4.1 
└── UNMET PEER DEPENDENCY react@15.1.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.13
npm WARN react-addons-test-utils@15.2.1 requires a peer of react@^15.2.1 but none was installed.
npm WARN react-dom@15.2.1 requires a peer of react@^15.2.1 but none was installed.
npm WARN app@1.0.0 No description

```

inside the api directory works fine

```
npm install getstream --save
api@1.0.0 /home/devekko/Projects/cabin-app/stream-react-example/api
└── getstream@3.4.1 

npm WARN api@1.0.0 No description
```

related?
https://github.com/facebook/react-native/issues/7803

**Comment by niccolox** [comment]
got past the npm error by updating the app/package.json to react@15.2.1

not sure if the entire example is now broken

but moving on and leaving open

```
npm install
app@1.0.0 /home/devekko/Projects/cabin-app/stream-react-example/app
└── react@15.2.1 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.13
npm WARN app@1.0.0 No description
```

```
 ~/Projects/cabin-app/stream-react-example/app (master *=) $ npm install getstream --save
app@1.0.0 /home/devekko/Projects/cabin-app/stream-react-example/app
└── getstream@3.4.1 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.13
npm WARN app@1.0.0 No description

```

**Comment by astrotars** [comment]
Thanks for the heads up @niccolox. Please keep us updated on your progress and feel free to reach out should you have any questions.

**Comment by niccolox** [comment]
no worries

api and app seem to work fine, although haven't completely got mapbox and algolia working yet

although I think that might be more cloud dashboard config than code

**Comment by kuhij** [comment]
sumit@Sumit-PC:~/Desktop/stream-react-example456$ cd app
sumit@Sumit-PC:~/Desktop/stream-react-example456/app$ npm start

> app@1.0.0 start /home/sumit/Desktop/stream-react-example456/app
> node ./bin/www

My app is hanging there it is not going forward or connecting to localhost.
Please Help me to sort out this problem
