### ISSUE TITLE
The demo site https://getstream.io/cabin/demo/ is not working.

### ISSUE THREAD

**Issue by SakhirAtwi** [GetStream/stream-react-example#53]
@nparsons08   After facebook login authentication, nothing happens. I don't that what is supposed to happen.
![screenshot_20180810_001646](https://user-images.githubusercontent.com/42070051/43920562-b691dccc-9c32-11e8-9c19-c68c34be2030.png)

After login, the same screen comes again. I think your site is outdated or something.

**Comment by astrotars** [comment]
@SakhirAtwi –

Do you have ad blockers installed? If so, which one?

What browser and version are you running?

**Comment by astrotars** [comment]
FYI - this is the latest version of Chrome on macOS

![2018-08-09 at 1 31 pm](https://user-images.githubusercontent.com/1328388/43921318-96e19f5c-9bd8-11e8-8873-bc52cd156040.png)

**Comment by SakhirAtwi** [comment]
@nparsons08 yeah I do have ad blockers install, sorry my bad :P, but the point is why should it be a trouble anyways?

**Comment by astrotars** [comment]
@SakhirAtwi  Ad blockers prevent some of our scripts from running and since it's in an iframe, it causes even more errors. Not sure why as I'm not in the ad blocking business ;) but I'd suggest disabling them if you're having trouble. Also, the Cabin demo works best in Chrome. Try an Incognito window if you're worried about ad tracking.

**Comment by SakhirAtwi** [comment]
@nparsons08  Alright, thanks :)

**Comment by SakhirAtwi** [comment]
@nparsons08 I notice you closed this issue already, but one last question, do the apps built on top of streamio has to be running in mobile devices or iframe? I mean can't we have UI for desktop? If so, why not configure your demo app for that, it would be great.

Cheers, Happy Coding.

-SakhirAtwi.

**Comment by astrotars** [comment]
@SakhirAtwi Sorry, I thought we had closed the conversation in general :) Cabin is one of our older example applications and a desktop version wasn't in the spec at that time. In the future, we may go down that road. Possibly even a native application. Keep an eye on the project! :) I'd suggest checking out Winds, which is available on macOS, Linux (any distro), Windows, and the web – https://getstream.io/winds.
