### ISSUE TITLE
please how do i get https to work for this app

### ISSUE THREAD

**Issue by vincentroman** [GetStream/stream-react-example#54]
i have been trying to get this app to work on a live server as i have noticed that i need https in order for the app to work with facebook login but i have tried using the free ssl certificates to install lets-encrypt but to no success please how do i get https to work on it... i do have the app working fine on my local machine though but not on the server like yours

**Comment by astrotars** [comment]
@vincentroman You'll need to implement with Nginx or something alike. I would recommend using a combination of https://letsencrypt.org/ and Nginx.

**Comment by vincentroman** [comment]
thanks
