### ISSUE TITLE
{"code":"InvalidCredentials","message":"No authorization token was found"}

### ISSUE THREAD

**Issue by vincentroman** [GetStream/stream-react-example#55]
@nparsons08 i have been having issue setting up this app for months as i have now osolved  many of the issues my self but still cant get pass this one my url is trendit.pro and my api is trendit.pro/api but every time i click the Facebook login it keeps reloading and i get this error if i visit the api link {"code":"InvalidCredentials","message":"No authorization token was found"} please help me thank you

**Comment by astrotars** [comment]
@vincentroman It looks like you haven't swapped out the Facebook key. Did you create a Facebook application under your Facebook developer account?

**Comment by vincentroman** [comment]
@nparsons08 thanks for the reply yes i did
you can take a look at my site header to see for for your self

**Comment by vincentroman** [comment]
@nparsons08  plus the app keeps reloading and returning 405 error method post not allowed on trendit.pro/api:8000

**Comment by vincentroman** [comment]
@nparsons08 pleas i need your help with the app please i have been working on this for months please help me out i have created the facebook login and still cant get it to work please help

**Comment by vincentroman** [comment]
@nparsons08 i am now getting another error after solving the first one here it is please i need a solution to this {"code":"MethodNotAllowedError","message":"GET is not allowed"}

**Comment by vincentroman** [comment]
@dwightgunning  i am now getting another error after solving the first one here it is please i need a solution to this {"code":"MethodNotAllowedError","message":"GET is not allowed"}
