### ISSUE TITLE
{"code":"InvalidCredentials","message":"No authorization token was found"}

### ISSUE THREAD

**Issue by vincentroman** [GetStream/stream-react-example#58]
@dwightgunning i have beent trying to login the app for months and now am getting have sent many message about this but no reply please help me

**Comment by dwightgunning** [comment]
Hi @vincentroman I'm no longer working at Stream and unfortunately don't have the spare time available to continue contributing to this project (nor a Facebook account to check the login issue you're experiencing). Sorry I can't be of more help.

**Comment by vincentroman** [comment]
ok thanks
