### ISSUE TITLE
typo for maps

### ISSUE THREAD

**Issue by niccolox** [GetStream/stream-react-example#6]
typo on http://blog.getstream.io/cabin-react-redux-example-app-mapbox/

app/routes/Location/Location.js doesnt exist 

its /app/modules/routes/Location/Location.js

**Comment by astrotars** [comment]
Thanks @niccolox! We'll get this taken care of ASAP.

**Comment by niccolox** [comment]
I also noticed maps crash.. haven't investigated why yet

**Comment by astrotars** [comment]
Keep us posted on the maps issue. Will also look into. For now, I'm going to close the issue.
