### ISSUE TITLE
Demo App has 500 Internal server error while getting users on first load

### ISSUE THREAD

**Issue by kinjalgiri** [GetStream/stream-react-example#9]
I am getting 500 Internal server error while getting users on first load as in image below
![getstream_demo](https://cloud.githubusercontent.com/assets/8242228/17082822/a4c6f92c-51a8-11e6-95a2-3f0aefef50bb.png)

**Comment by miladr0** [comment]
Same problem, it's not working

**Comment by astrotars** [comment]
Thanks for the heads up @Blackops404 @kinjalgiri! Problem fixed now :) 👍

**Comment by miladr0** [comment]
i tried again it's not fixed

**Comment by astrotars** [comment]
Can you provide a screenshot of your browser console?

**Comment by miladr0** [comment]
![capture](https://cloud.githubusercontent.com/assets/6761526/17115264/cbb508a6-52c7-11e6-8757-042cc3fedc82.PNG)
